"""This package contains modules that allow the generation of experiment XMLs.

An XML can be generated by constraining parameters of virtual clusters, while
ensuring that the clusters are feasible. Parameters include number of VMs,
VM size, pinning strategies, etc.

""" 