#!/bin/bash
#
# Giacomo Mc Evoy - giacomo@lncc.br
# LNCC Brazil 2013
# Adapted from job.PARPARBench
# christian.simmendinger@t-systems.com
#
#PBS -l walltime=120:00
#PBS -l nodes=&PBS_TOPOLOGY
#PBS -N PARPACBench
#PBS -t 1-11
#PBS -o /tmp/vespa/tests/deploy/parpac/nc16-cpv4-idf8-psBAL_ONE/ad9513de1bf9a1865050460e904a78904976a648927f07d0be134995cc9a3d55/pbs.out
#PBS -e /tmp/vespa/tests/deploy/parpac/nc16-cpv4-idf8-psBAL_ONE/ad9513de1bf9a1865050460e904a78904976a648927f07d0be134995cc9a3d55/pbs.err

# Var PBS_NODEFILE contains the node names (repeated)

# Execution parameters 
rnum=$PBS_ARRAYID		# Iteration of experiment (PBS)

# Deployment parameters
np=&NC

# Application parameters
name=parpac-2013-04-06-08:55

echo "Running PBS application: PARPACBench"
echo "Execution number: $rnum"

# Sort (don't copy) file with node names, to ensure uniqueness
EXEC_PROCS=/tmp/pbs-$name-procs.txt
sort $PBS_NODEFILE > $EXEC_PROCS

# Output dir for this execution set 
rnum=$(printf "%03d\n" $rnum)
EXEC_OUTPUT_DIR=/tmp/vespa/tests/deploy/parpac/nc16-cpv4-idf8-psBAL_ONE/ad9513de1bf9a1865050460e904a78904976a648927f07d0be134995cc9a3d55/${name}-${rnum}
STDOUT=std.out
STDERR=std.err

# Prepare execution
export PATH=$PATH:/usr/local/bin
mkdir -p $EXEC_OUTPUT_DIR
cd /home/giacomo2/shared/PARPACBench-1.4

cp $PBS_NODEFILE /tmp/pbs-nodefile.txt

# Also monitor nodes?
if [ 'True' == 'True' ]; then
	echo -e '&PHYSICAL_NODE_LIST' >> /tmp/pbs-nodefile.txt
fi

# Start monitoring
$HOME/vespa/monitor/monitor-start-pbs.sh /tmp/pbs-nodefile.txt sysstat

# The actual invocation of the application
/usr/bin/time -f '%C\nUser\tSystem\tEllapsed\n%U\t%S\t%e' -a -o $EXEC_OUTPUT_DIR/../times.txt mpirun --mca plm_rsh_agent "ssh -q -o StrictHostKeyChecking=no" &MPI_BTL --bind-to socket PARPACBench firstarg secondarg > $EXEC_OUTPUT_DIR/$STDOUT 2> $EXEC_OUTPUT_DIR/$STDERR

# Stop monitoring iteratively
$HOME/vespa/monitor/monitor-stop-pbs.sh /tmp/pbs-nodefile.txt $EXEC_OUTPUT_DIR sysstat

# Post-processing of output may be necessary
if [ 'Y' == 'Y' ]; then
	cp /home/giacomo2/shared/PARPACBench-1.4/results/parpacbench_${np}cpu_32lbu.out $EXEC_OUTPUT_DIR/custom.out
fi

# Pre-process the monitor files, to save space
$HOME/vespa/monitor/monitor-preprocess-pbs.sh $EXEC_OUTPUT_DIR /tmp/pbs-nodefile.txt sysstat
