---
- hosts: all
  gather_facts: no
  tasks:
    - name: Create VM dirs
      file: dest={{ repo_root }}/{{ inventory_hostname_short }}/{{ item }} state=directory
      with_items: "{{ vmNames }}"
      sudo: no

    - name: Replicate VM images
      shell: cp -v {{ repo_root }}/{{ repo_base }}/* {{ repo_root }}/{{ inventory_hostname_short }}/{{ item }}
      with_items: "{{ vmNames }}"
      sudo: yes
