---
- hosts: all
  gather_facts: no
  tasks:
    - name: Set VM hostnames 
      hostname: name={{ inventory_hostname_short }}
      remote_user: root

    - name: Update /etc/hosts 
      copy: src={{ etc_hosts }} dest=/etc/hosts
      remote_user: root

    - name: Create Vespa directory
      file: dest={{ vespa_dir }} state=directory

    - name: Copy monitoring files to VMs
      synchronize: src={{ vespa_dir }}/monitor dest={{ vespa_dir }}

    - name: Copy GRUB configuration to VMs
      synchronize: src={{ vespa_dir }}/data-input/grub dest=/etc/default/
      remote_user: root

    - name: Update GRUB
      command: update-grub
      remote_user: root

    - name: Copy Torque configuration to VMs
      synchronize: src={{ vespa_dir }}/data-input/torque-mom dest=/etc/init.d/
      remote_user: root
